# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
orbs:
  maven: circleci/maven@0.0.12
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  maventest:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Run mvn tests
          command: |
            mkdir -p ./test-results/junit
            mvn test 
      # Save artifacts
      - store_artifacts:
          path: ./target/surefire-reports

      # Upload test results
      - store_test_results:
          path: ./target/surefire-reports

  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  maven_test:
    jobs:
      - maventest
       # test_result_path: target/surefire-reports  # checkout, build, test, and upload test results
  say-hello-workflow:
    jobs:
      - say-hello
